const assert = require('node:assert/strict');
const fs = require('node:fs');
const explorer = fs.readFileSync('explorer.html','utf8');
const nav = fs.readFileSync('bottom-nav.js','utf8');
assert(!nav.includes("['explorer.html'"), 'public navigation must not expose Explorer');
assert(explorer.includes('Museum Archive'));
for (const value of ['missing','draft','published','recent']) assert(explorer.includes(`value="${value}"`));
assert(explorer.includes('BillyCuratorData.draftList()'));
assert(explorer.includes('BillyCuratorData.listPublished()'));
assert(explorer.includes('BillyDiscovery.newestDate(all)'));
assert(explorer.includes('data-action="inspect"'));
assert(explorer.includes('&curator=1'));
console.log('curator-explorer-foundation.test.js passed');
