const fs = require('fs');
const vm = require('vm');
const path = require('path');
const root = path.resolve(__dirname, '..');
const store = new Map();
const localStorage = {setItem:(k,v)=>store.set(k,String(v)),getItem:k=>store.has(k)?store.get(k):null,removeItem:k=>store.delete(k)};
const ctx = {window:{}, localStorage, console, JSON, Map, Set, Date};
ctx.window.window=ctx.window;
vm.createContext(ctx);
for (const file of ['billy-storage.js','billy-sync-manager.js','billy-repositories.js']) vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});
const repos=ctx.window.BillyRepositories;
if (!repos || repos.version !== 5) throw new Error('Repository layer failed to initialize');
repos.settings.set('collection.hideEmptySlots',true);
if (repos.settings.get('collection.hideEmptySlots',false)!==true) throw new Error('Settings repository failed');
repos.explorer.saveState({query:'frog'});
if (repos.explorer.getState(null).query!=='frog') throw new Error('Explorer repository failed');
repos.profile.saveVotes({'a+b':'funny'});
if (repos.profile.getVotes()['a+b']!=='funny') throw new Error('Profile repository failed');
console.log('repository foundation tests passed');
