const API_VERSION = '2.2.9';
const SCHEMA_VERSION = 3;
const corsHeaders = {'access-control-allow-origin':'*','access-control-allow-methods':'GET, PUT, POST, OPTIONS','access-control-allow-headers':'content-type, x-curator-key'};
const json=(body,init={})=>new Response(JSON.stringify(body),{...init,headers:{...corsHeaders,'content-type':'application/json; charset=utf-8',...(init.headers||{})}});
const requireDb=env=>{if(!env.DB)throw new Error('D1 database is not bound');return env.DB};
const validId=value=>typeof value==='string'&&/^[A-Za-z0-9_|+\-]{1,256}$/.test(value);
const validIds=values=>Array.isArray(values)&&values.every(validId);
const validMashupId=value=>typeof value==='string'&&value.length>0&&value.length<=256&&!/[\u0000-\u001f]/.test(value);
const userRoute=path=>{const m=path.match(/^\/api\/users\/([^/]+)\/(favorites|progress)$/);return m?{userId:decodeURIComponent(m[1]),resource:m[2]}:null};
const deviceRoute=path=>{const m=path.match(/^\/api\/devices\/([^/]+)$/);return m?decodeURIComponent(m[1]):null};
const blurbletRoute=path=>{let m=path.match(/^\/api\/blurblets\/([^/]+)$/);if(m)return{mashupId:decodeURIComponent(m[1]),curator:false};m=path.match(/^\/api\/curator\/blurblets\/([^/]+)$/);return m?{mashupId:decodeURIComponent(m[1]),curator:true}:null};
const getProgress=async(env,userId)=>{const result=await requireDb(env).prepare('SELECT mashup_id, seen, favorite FROM mashup_progress WHERE user_id = ?1 AND (seen = 1 OR favorite = 1) ORDER BY mashup_id').bind(userId).all();const seen=[],favorites=[];for(const row of result.results||[]){if(row.seen)seen.push(row.mashup_id);if(row.favorite)favorites.push(row.mashup_id)}return{seen,favorites}};
const putProgress=async(env,userId,progress)=>{const db=requireDb(env),seen=[...new Set(progress.seen)],favorites=[...new Set(progress.favorites)],ids=[...new Set([...seen,...favorites])],seenSet=new Set(seen),favoriteSet=new Set(favorites);const statements=[db.prepare("INSERT INTO users (id, display_name) VALUES (?1, '') ON CONFLICT(id) DO UPDATE SET updated_at=CURRENT_TIMESTAMP").bind(userId),db.prepare('UPDATE mashup_progress SET seen=0, favorite=0, updated_at=CURRENT_TIMESTAMP WHERE user_id=?1').bind(userId),...ids.map(id=>db.prepare('INSERT INTO mashup_progress (user_id,mashup_id,seen,favorite,first_seen_at,updated_at) VALUES (?1,?2,?3,?4,CASE WHEN ?3=1 THEN CURRENT_TIMESTAMP ELSE NULL END,CURRENT_TIMESTAMP) ON CONFLICT(user_id,mashup_id) DO UPDATE SET seen=?3,favorite=?4,first_seen_at=CASE WHEN ?3=1 THEN COALESCE(mashup_progress.first_seen_at,CURRENT_TIMESTAMP) ELSE mashup_progress.first_seen_at END,updated_at=CURRENT_TIMESTAMP').bind(userId,id,seenSet.has(id)?1:0,favoriteSet.has(id)?1:0))];await db.batch(statements);return{seen:seen.sort(),favorites:favorites.sort()}};
const registerDevice=async(env,deviceId,metadata={})=>{const db=requireDb(env);await db.batch([db.prepare("INSERT INTO users (id, provider, display_name) VALUES (?1, 'anonymous-device', '') ON CONFLICT(id) DO UPDATE SET updated_at=CURRENT_TIMESTAMP").bind(deviceId),db.prepare('INSERT INTO devices (id,user_id,metadata_json,last_seen_at) VALUES (?1,?1,?2,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET metadata_json=?2,last_seen_at=CURRENT_TIMESTAMP').bind(deviceId,JSON.stringify(metadata||{}))]);return{deviceId,userId:deviceId,status:'registered'}};
const getDevice=async(env,deviceId)=>await requireDb(env).prepare('SELECT id,user_id,created_at,last_seen_at FROM devices WHERE id=?1').bind(deviceId).first()||null;
const getBlurblet=async(env,mashupId)=>await requireDb(env).prepare('SELECT mashup_id,published_text,published_at,updated_at FROM curator_blurblets WHERE mashup_id=?1').bind(mashupId).first()||null;
const publishBlurblet=async(env,mashupId,text)=>{const clean=String(text||'').trim();await requireDb(env).prepare("INSERT INTO curator_blurblets (mashup_id,published_text,published_at,updated_at) VALUES (?1,?2,CASE WHEN ?2='' THEN NULL ELSE CURRENT_TIMESTAMP END,CURRENT_TIMESTAMP) ON CONFLICT(mashup_id) DO UPDATE SET published_text=?2,published_at=CASE WHEN ?2='' THEN NULL ELSE CURRENT_TIMESTAMP END,updated_at=CURRENT_TIMESTAMP").bind(mashupId,clean).run();return{mashupId,text:clean,published:!!clean}};
export default{async fetch(request,env={}){const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...corsHeaders,'access-control-max-age':'86400'}});if(request.method==='GET'&&url.pathname==='/api/health')return json({ok:true,service:'Billy Labs API',version:API_VERSION,schemaVersion:SCHEMA_VERSION,storage:env.DB?'d1-bound':'d1-not-bound'});try{const br=blurbletRoute(url.pathname);if(br){if(!validMashupId(br.mashupId))return json({ok:false,error:'Invalid mashup ID'},{status:400});if(!br.curator&&request.method==='GET'){const row=await getBlurblet(env,br.mashupId);return json({ok:true,mashupId:br.mashupId,text:row?.published_text||'',publishedAt:row?.published_at||null});}if(br.curator&&request.method==='PUT'){if(!env.CURATOR_PUBLISH_KEY)return json({ok:false,error:'Curator publishing is not configured'},{status:503});if(request.headers.get('x-curator-key')!==env.CURATOR_PUBLISH_KEY)return json({ok:false,error:'Unauthorized'},{status:401});const body=await request.json().catch(()=>null);if(!body||typeof body.text!=='string'||body.text.length>1000)return json({ok:false,error:'text must be a string up to 1000 characters'},{status:400});return json({ok:true,...await publishBlurblet(env,br.mashupId,body.text)});}return json({ok:false,error:'Method not allowed'},{status:405});}
if(request.method==='POST'&&url.pathname==='/api/devices/register'){const body=await request.json().catch(()=>null);if(!body||!validId(body.deviceId))return json({ok:false,error:'Invalid device ID'},{status:400});return json({ok:true,...await registerDevice(env,body.deviceId,body.metadata)});}const deviceId=deviceRoute(url.pathname);if(deviceId&&request.method==='GET'){if(!validId(deviceId))return json({ok:false,error:'Invalid device ID'},{status:400});const device=await getDevice(env,deviceId);return device?json({ok:true,device}):json({ok:false,error:'Device not found'},{status:404});}const matched=userRoute(url.pathname);if(matched){const{userId,resource}=matched;if(!validId(userId))return json({ok:false,error:'Invalid user ID'},{status:400});if(request.method==='GET'){const progress=await getProgress(env,userId);return resource==='favorites'?json({ok:true,userId,favorites:progress.favorites}):json({ok:true,userId,...progress});}if(request.method==='PUT'){const body=await request.json().catch(()=>null);if(resource==='favorites'){if(!body||!validIds(body.favorites))return json({ok:false,error:'favorites must be an array of mashup IDs'},{status:400});const current=await getProgress(env,userId),progress=await putProgress(env,userId,{seen:current.seen,favorites:body.favorites});return json({ok:true,userId,favorites:progress.favorites});}if(!body||!validIds(body.seen)||!validIds(body.favorites))return json({ok:false,error:'seen and favorites must be arrays of mashup IDs'},{status:400});return json({ok:true,userId,...await putProgress(env,userId,body)});}return json({ok:false,error:'Method not allowed'},{status:405});}}catch(error){return json({ok:false,error:error.message},{status:error.message==='D1 database is not bound'?503:500});}return json({ok:false,error:'Not found',path:url.pathname},{status:404});}};
